### ISSUE TITLE
Is the training script and checkpoint of the hifigan vocoder available?

### ISSUE THREAD

**Issue by Aisaka0v0** [haidog-yaqub/DPMTSE#1]

**Comment by haidog-yaqub** [comment]
Hi, I will upload the link for checkpoint soon, and the training script is as same as the original hifigan repo if you want to train your own vocoder.

**Comment by kouichi310** [comment]
Hi.
I would like a checkpoint too, where is it?
I could not use the checkpoint in the hifigan repository 😢

**Comment by haidog-yaqub** [comment]
> Hi. I would like a checkpoint too, where is it? I could not use the checkpoint in the hifigan repository 😢

Hi i have updated the checkpoints, training code, and test demo. please check the latest readme.

**Comment by kouichi310** [comment]
thank you!
It's really helpful! 🤗
